<?php

declare(strict_types=1);

namespace EasyCorp\Bundle\EasyAdminBundle\Cache;

use Symfony\Component\Config\ConfigCache;
use Symfony\Component\Config\Resource\FileResource;

class ConfigCacheManager
{
    private ConfigCache $configCache;
    private array $adminConfigPaths;

    public function __construct(string $cacheDir, array $adminConfigPaths, bool $debug)
    {
        $this->configCache = new ConfigCache($cacheDir.'/easy_admin_config.php', $debug);
        $this->adminConfigPaths = $adminConfigPaths;
    }

    public function getConfig(): ?array
    {
        if ($this->configCache->isFresh()) {
            return require $this->configCache->getPath();
        }

        return null;
    }

    public function save(array $config): void
    {
        $this->configCache->write($this->backendConfigContent($config), array_map(function (string $path): FileResource {
            return new FileResource($path);
        }, $this->adminConfigPaths));
    }

    public function invalidate(): void
    {
        @unlink($this->configCache->getPath());
    }

    private function backendConfigContent(array $config): string
    {
        $content = var_export($config, true);

        return <<<EOF
<?php

/**
 * This file has been auto-generated by EasyAdminBundle
 */

return {$content};

EOF;
    }
}
